FROM us-docker.pkg.dev/cloud-tpu-images/inference/maxengine-server:v0.2.2
RUN pip install -U "jax[tpu]" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html && \
    pip install -U libtpu-nightly==0.1.dev20240903 -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
RUN mv /usr/local/lib/python3.10/dist-packages/jax/_src/hardware_utils.py \
/usr/local/lib/python3.10/dist-packages/jax/_src/hardware_utils.py.bak && \
sed -s "s/'0x0062'/'0x0062',\n    '0x006f'/g" \
/usr/local/lib/python3.10/dist-packages/jax/_src/hardware_utils.py.bak \
> /usr/local/lib/python3.10/dist-packages/jax/_src/hardware_utils.py